Feature/vaccinecer 2186 log key identifier during creation
admin-ch/CovidCertificate-Management-Service pull request #327
Opened 2022-04-14 09:26 UTC by haraldloesing

2022-04-14 11:12 UTC, mofobo-bit requested changes

2022-04-14 11:12 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/test/TestController.java
> +                            !signingInformation.getCertificateAlias().isBlank()) {
import org.apache.commons.lang3.StringUtils;

StringUtils.isNotBlank(signingInformation.getCertificateAlias())

2022-04-25 07:32 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/client/signing/SigningInformationDto.java
> +    public static class SigningInformationDtoBuilder {
Nope, as the Setter is invoked after creation. The Attribute is a derived Attribute calculated during the signing process.

2022-04-25 07:40 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/test/TestController.java
> +                            !signingInformation.getCertificateAlias().isBlank()) {
Done

2022-04-25 07:40 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/api/response/CovidCertificateResponseEnvelope.java
> +    private String usedKexIdentifier;
Done

2022-04-25 12:19 UTC, iris-hunkeler approved these changes

2022-04-25 12:21 UTC, merged